import React from 'react';
import { ActiveNavView } from '../../context/ErpContext';
import {
  LayoutDashboard,
  Boxes,
  Layers,
  Barcode,
  ShoppingBag,
  BarChart3,
  ShieldCheck,
  UserCheck,
  Contact,
  ShoppingCart,
  Truck,
  Receipt,
  ClipboardList,
  WalletCards,
  Users,
  Clock,
  Sparkles,
  Plus,
  FileText,
  RotateCcw,
  Save,
  PackageCheck,
  History,
  Settings,
  Eye,
  Camera,
  Calendar,
  DollarSign,
  TrendingUp,
  PieChart,
  Tag,
  ArrowRightLeft,
  Building2,
  UserPlus,
  FileSpreadsheet,
} from 'lucide-react';

export interface NavSubOption {
  id: string;
  label: string;
  description: string;
  icon: React.ComponentType<{ className?: string }>;
  badge?: string;
  tag?: 'Tab' | 'Action' | 'Filter' | 'Preset';
}

export interface NavItemSubConfig {
  id: ActiveNavView;
  title: string;
  subtitle: string;
  icon: React.ComponentType<{ className?: string }>;
  accentColor: string; // Tailwind color name for styling
  subOptions: NavSubOption[];
}

export const NAV_SUB_CONFIG: Record<ActiveNavView, NavItemSubConfig> = {
  dashboard: {
    id: 'dashboard',
    title: 'Dashboard',
    subtitle: 'High-level business overview & KPIs',
    icon: LayoutDashboard,
    accentColor: 'blue',
    subOptions: [
      {
        id: 'overview',
        label: 'Executive Overview',
        description: 'Gross sales, net cash, receivables & branch KPIs',
        icon: LayoutDashboard,
        tag: 'Tab',
      },
      {
        id: 'sales-trend',
        label: 'Sales Revenue Trend',
        description: '14-day and 30-day sales volume charts',
        icon: TrendingUp,
        tag: 'Tab',
      },
      {
        id: 'top-products',
        label: 'Top Velocity Products',
        description: 'Highest revenue & top-selling SKU rankings',
        icon: Boxes,
        tag: 'Tab',
      },
    ],
  },
  items: {
    id: 'items',
    title: 'Items & Catalog',
    subtitle: 'Master catalog, bundles & pricing',
    icon: Boxes,
    accentColor: 'blue',
    subOptions: [
      {
        id: 'products',
        label: 'Products Catalog',
        description: 'Browse all SKUs, prices, stock levels & barcodes',
        icon: Boxes,
        tag: 'Tab',
      },
      {
        id: 'combos',
        label: 'Combos & Bundles',
        description: 'Multi-item kit packages and bundle availability',
        icon: Layers,
        tag: 'Tab',
      },
      {
        id: 'add-product',
        label: 'Add New Product',
        description: 'Create a new SKU in the central catalog',
        icon: Plus,
        tag: 'Action',
      },
      {
        id: 'add-combo',
        label: 'Create Combo Bundle',
        description: 'Assemble a bundle package from existing items',
        icon: Sparkles,
        tag: 'Action',
      },
    ],
  },
  customers: {
    id: 'customers',
    title: 'Customers',
    subtitle: 'Customer profiles, dues & loyalty',
    icon: UserCheck,
    accentColor: 'emerald',
    subOptions: [
      {
        id: 'directory',
        label: 'Customer Directory',
        description: 'Customer profiles, purchase history & phone numbers',
        icon: Users,
        tag: 'Tab',
      },
      {
        id: 'loyalty',
        label: 'Loyalty Program',
        description: 'Reward milestones, points accumulation & tiers',
        icon: Sparkles,
        tag: 'Tab',
      },
      {
        id: 'new-customer',
        label: 'Add Customer',
        description: 'Register a new customer account',
        icon: UserPlus,
        tag: 'Action',
      },
    ],
  },
  parties: {
    id: 'parties',
    title: 'Parties Ledger',
    subtitle: 'Customers & suppliers directory',
    icon: Contact,
    accentColor: 'indigo',
    subOptions: [
      {
        id: 'all',
        label: 'All Parties',
        description: 'Unified list of all customers and vendor accounts',
        icon: Contact,
        tag: 'Filter',
      },
      {
        id: 'customers',
        label: 'Customers (To Collect)',
        description: 'Accounts with receivables and unpaid customer balances',
        icon: UserCheck,
        tag: 'Filter',
      },
      {
        id: 'suppliers',
        label: 'Suppliers (To Pay)',
        description: 'Vendors with outstanding procurement payables',
        icon: Building2,
        tag: 'Filter',
      },
      {
        id: 'new-customer',
        label: 'Add Customer',
        description: 'Register a new customer profile',
        icon: UserPlus,
        tag: 'Action',
      },
      {
        id: 'new-supplier',
        label: 'Add Supplier',
        description: 'Register a new procurement supplier',
        icon: Plus,
        tag: 'Action',
      },
    ],
  },
  enquiries: {
    id: 'enquiries',
    title: 'Enquiries',
    subtitle: 'Customer leads & pipeline',
    icon: ClipboardList,
    accentColor: 'violet',
    subOptions: [
      {
        id: 'all',
        label: 'All Enquiries',
        description: 'Manage active customer enquiries and follow-ups',
        icon: ClipboardList,
        tag: 'Tab',
      },
      {
        id: 'new-item-requests',
        label: 'New Item Requests',
        description: 'Customer requests for items not in current catalog',
        icon: Tag,
        tag: 'Tab',
      },
      {
        id: 'new',
        label: 'Record New Enquiry',
        description: 'Log an inbound customer product inquiry',
        icon: Plus,
        tag: 'Action',
      },
    ],
  },
  'pending-orders': {
    id: 'pending-orders',
    title: 'Pending Orders',
    subtitle: 'Customer order fulfillment pipeline',
    icon: Clock,
    accentColor: 'amber',
    subOptions: [
      {
        id: 'ALL',
        label: 'All Orders',
        description: 'Full pending order pipeline across branches',
        icon: Clock,
        tag: 'Filter',
      },
      {
        id: 'Draft',
        label: 'Draft Orders',
        description: 'Unconfirmed orders pending customer approval',
        icon: FileText,
        tag: 'Filter',
      },
      {
        id: 'Confirmed',
        label: 'Confirmed Orders',
        description: 'Approved orders ready for picking and packing',
        icon: PackageCheck,
        tag: 'Filter',
      },
      {
        id: 'Dispatched',
        label: 'Dispatched Orders',
        description: 'Orders shipped or out for delivery',
        icon: Truck,
        tag: 'Filter',
      },
    ],
  },
  challans: {
    id: 'challans',
    title: 'Delivery Challan',
    subtitle: 'Dispatch notes & delivery documentation',
    icon: Truck,
    accentColor: 'sky',
    subOptions: [
      {
        id: 'new',
        label: 'Create Challan',
        description: 'Issue a delivery challan for dispatched stock',
        icon: Plus,
        tag: 'Tab',
      },
      {
        id: 'history',
        label: 'Challan History',
        description: 'View past delivery challans, recipients & printouts',
        icon: History,
        tag: 'Tab',
      },
    ],
  },
  inventory: {
    id: 'inventory',
    title: 'Inventory',
    subtitle: 'Warehouse stock, transfers & audits',
    icon: Layers,
    accentColor: 'emerald',
    subOptions: [
      {
        id: 'items',
        label: 'Regular Items Stock',
        description: 'Live physical quantities, low stock & reorder levels',
        icon: Boxes,
        tag: 'Tab',
      },
      {
        id: 'combos',
        label: 'Combos & Kits',
        description: 'Kit availability assembled from on-hand components',
        icon: Layers,
        tag: 'Tab',
      },
      {
        id: 'transfer',
        label: 'Transfer Stock',
        description: 'Send physical inventory between branch locations',
        icon: ArrowRightLeft,
        tag: 'Action',
      },
      {
        id: 'transfer-history',
        label: 'Transfer History',
        description: 'Audit log of past inter-branch shipments and receipts',
        icon: History,
        tag: 'Action',
      },
      {
        id: 'audit',
        label: 'Stock Audit Trail',
        description: 'Detailed log of manual adjustments and reconciliations',
        icon: History,
        tag: 'Action',
      },
    ],
  },
  invoices: {
    id: 'invoices',
    title: 'Sales & Billing',
    subtitle: 'Invoicing, POS, quotes & credit notes',
    icon: Receipt,
    accentColor: 'blue',
    subOptions: [
      {
        id: 'ledger',
        label: 'Sales Ledger',
        description: 'Master list of issued tax invoices & payments',
        icon: Receipt,
        tag: 'Tab',
      },
      {
        id: 'new',
        label: 'New Sale / Billing POS',
        description: 'Create a new invoice in multi-tab billing workspace',
        icon: Plus,
        tag: 'Action',
      },
      {
        id: 'estimates',
        label: 'Quotation History',
        description: 'Past quotes issued, conversion status & PDFs',
        icon: FileText,
        tag: 'Tab',
      },
      {
        id: 'returns',
        label: 'Sales Returns',
        description: 'Processed returns, credit notes & returned stock',
        icon: RotateCcw,
        tag: 'Tab',
      },
      {
        id: 'draft-sales',
        label: 'Saved Sale Drafts',
        description: 'Locally saved invoice drafts in progress',
        icon: Save,
        tag: 'Tab',
      },
      {
        id: 'draft-quotes',
        label: 'Saved Quote Drafts',
        description: 'Locally saved quotation drafts in progress',
        icon: Save,
        tag: 'Tab',
      },
    ],
  },
  barcodes: {
    id: 'barcodes',
    title: 'Barcode Printing',
    subtitle: 'Label generation & multi-sheet printing',
    icon: Barcode,
    accentColor: 'slate',
    subOptions: [
      {
        id: 'generate',
        label: 'Barcode Generator',
        description: 'Search catalog items and build printable barcode queue',
        icon: Barcode,
        tag: 'Tab',
      },
      {
        id: 'preview',
        label: 'Sheet Print Preview',
        description: 'Preview A4 multi-label layout before printing',
        icon: Eye,
        tag: 'Action',
      },
      {
        id: 'settings',
        label: 'Label & Printer Settings',
        description: 'Configure label sizes (38x21, 50x25, etc.) and margins',
        icon: Settings,
        tag: 'Action',
      },
    ],
  },
  'cash-register': {
    id: 'cash-register',
    title: 'Daily Cash Register',
    subtitle: 'Daily drawer reconciliation & cash expenses',
    icon: WalletCards,
    accentColor: 'teal',
    subOptions: [
      {
        id: 'register',
        label: 'Daily Cash Drawer',
        description: 'Opening balance, daily cash sales, petty expenses & closing',
        icon: WalletCards,
        tag: 'Tab',
      },
      {
        id: 'history',
        label: 'Register History',
        description: 'Past daily closing records and shift balances',
        icon: History,
        tag: 'Action',
      },
      {
        id: 'recurring',
        label: 'Recurring Expenses',
        description: 'Manage monthly fixed templates (rent, utilities, etc.)',
        icon: Calendar,
        tag: 'Tab',
      },
    ],
  },
  purchases: {
    id: 'purchases',
    title: 'Purchases',
    subtitle: 'Supplier procurement & inward stock',
    icon: ShoppingBag,
    accentColor: 'amber',
    subOptions: [
      {
        id: 'orders',
        label: 'Purchase Orders',
        description: 'Issued POs, delivery statuses & inward goods receipts',
        icon: ShoppingBag,
        tag: 'Tab',
      },
      {
        id: 'vendors',
        label: 'Suppliers Directory',
        description: 'Registered vendors, contacts & payable balances',
        icon: Building2,
        tag: 'Tab',
      },
      {
        id: 'issue-po',
        label: 'Issue Purchase Order',
        description: 'Draft a new procurement order to a supplier',
        icon: Plus,
        tag: 'Action',
      },
      {
        id: 'add-vendor',
        label: 'Add Supplier',
        description: 'Register a new vendor or procurement partner',
        icon: Plus,
        tag: 'Action',
      },
    ],
  },
  hrm: {
    id: 'hrm',
    title: 'Attendance & HRM',
    subtitle: 'Staff check-ins, wages & directory',
    icon: Users,
    accentColor: 'rose',
    subOptions: [
      {
        id: 'attendance',
        label: 'Staff Attendance',
        description: 'Daily check-ins, punch logs, overtime & working hours',
        icon: Clock,
        tag: 'Tab',
      },
      {
        id: 'payroll',
        label: 'Payroll Processing',
        description: 'Monthly payroll calculation, deductions & pay slips',
        icon: DollarSign,
        tag: 'Tab',
      },
      {
        id: 'employees',
        label: 'Staff Directory',
        description: 'Employee profiles, designations, branches & contacts',
        icon: Users,
        tag: 'Tab',
      },
      {
        id: 'salary',
        label: 'Salary Structure',
        description: 'Base pay rules, allowances & hourly rates',
        icon: DollarSign,
        tag: 'Tab',
      },
      {
        id: 'kiosk',
        label: 'Punch Kiosk',
        description: 'Open camera check-in terminal for staff punch-in',
        icon: Camera,
        tag: 'Action',
      },
      {
        id: 'new-employee',
        label: 'Add Employee',
        description: 'Register a new staff member in the system',
        icon: UserPlus,
        tag: 'Action',
      },
    ],
  },
  reports: {
    id: 'reports',
    title: 'Reports & Analytics',
    subtitle: 'Financial statements, P&L & GST',
    icon: BarChart3,
    accentColor: 'indigo',
    subOptions: [
      {
        id: 'sales',
        label: 'Sales Register & Ledger',
        description: 'Sales revenue breakdowns, payment modes & customers',
        icon: BarChart3,
        tag: 'Tab',
      },
      {
        id: 'pnl',
        label: 'Branch P&L Summary',
        description: 'Revenue, cost of goods, gross margins & operating profit',
        icon: TrendingUp,
        tag: 'Tab',
      },
      {
        id: 'stock-valuation',
        label: 'Stock Valuation Report',
        description: 'Total asset valuation, purchase cost vs retail value',
        icon: Boxes,
        tag: 'Tab',
      },
      {
        id: 'enquiry-conversion',
        label: 'Enquiry Conversion',
        description: 'Lead-to-invoice conversion percentages & sales pipeline',
        icon: PieChart,
        tag: 'Tab',
      },
      {
        id: 'purchase-orders',
        label: 'Purchase Orders Report',
        description: 'Procurement volume, spend by vendor & inward status',
        icon: ShoppingBag,
        tag: 'Tab',
      },
      {
        id: 'gst',
        label: 'GST Filing (GSTR-1 & 3B)',
        description: 'HSN summaries, tax slab liability & exportable data',
        icon: FileSpreadsheet,
        tag: 'Tab',
      },
      {
        id: 'payroll',
        label: 'Payroll Summary Report',
        description: 'Departmental salary disbursements & wage totals',
        icon: DollarSign,
        tag: 'Tab',
      },
    ],
  },
  shopify: {
    id: 'shopify',
    title: 'Online Store (Shopify)',
    subtitle: 'E-commerce sync & incoming orders',
    icon: ShoppingCart,
    accentColor: 'emerald',
    subOptions: [
      {
        id: 'orders',
        label: 'Store Orders & Sync',
        description: 'Recent Shopify web orders, payment status & fulfillment',
        icon: ShoppingCart,
        tag: 'Tab',
      },
      {
        id: 'import-products',
        label: 'Import Products from Store',
        description: 'Download online products into local ERP catalog by SKU',
        icon: Sparkles,
        tag: 'Action',
      },
    ],
  },
  'ai-assistant': {
    id: 'ai-assistant',
    title: 'Beta AI Assistant',
    subtitle: 'Conversational assistant for ERP metrics',
    icon: Sparkles,
    accentColor: 'fuchsia',
    subOptions: [
      {
        id: 'chat',
        label: 'Ask AI Assistant',
        description: 'Natural language queries regarding inventory, sales & staff',
        icon: Sparkles,
        tag: 'Tab',
      },
    ],
  },
  access: {
    id: 'access',
    title: 'Access Control',
    subtitle: 'Permissions matrix, staff PINs & audit log',
    icon: ShieldCheck,
    accentColor: 'amber',
    subOptions: [
      {
        id: 'roles',
        label: 'Role Permissions Matrix',
        description: 'Configure module access and action guards for all roles',
        icon: ShieldCheck,
        tag: 'Tab',
      },
      {
        id: 'staff',
        label: 'Staff Accounts & PINs',
        description: 'Manage individual user PINs, logins and branch locks',
        icon: Users,
        tag: 'Tab',
      },
      {
        id: 'audit',
        label: 'Security Audit Log',
        description: 'System login records, unauthorized attempts & modifications',
        icon: History,
        tag: 'Tab',
      },
    ],
  },
  estimates: {
    id: 'estimates',
    title: 'Quotations',
    subtitle: 'Sales quotation management',
    icon: FileText,
    accentColor: 'blue',
    subOptions: [
      {
        id: 'estimates',
        label: 'Quotations History',
        description: 'View and convert past customer price estimates',
        icon: FileText,
        tag: 'Tab',
      },
      {
        id: 'new-quote',
        label: 'Create New Quotation',
        description: 'Draft a price quotation for customer review',
        icon: Plus,
        tag: 'Action',
      },
    ],
  },
};
